CREATE DATABASE aperture;

USE aperture;

CREATE TABLE usuario (
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(150),
idade INT,
profissao VARCHAR(45),
email VARCHAR(150),
senha VARCHAR(45),
dtCriacao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recordes (
idRecordes INT PRIMARY KEY AUTO_INCREMENT,
segundos INT,
tempo VARCHAR(10),
dtRecorde DATETIME DEFAULT CURRENT_TIMESTAMP,
fkUsuario INT,
FOREIGN KEY (fkUsuario) REFERENCES usuario(idUsuario)
);

CREATE TABLE quiz (
idQuiz INT PRIMARY KEY AUTO_INCREMENT,
resultado TINYINT,
dtQuiz DATETIME DEFAULT CURRENT_TIMESTAMP
);